version: '2'
catalog:
  name: cheztone-load-balancer
  version: 1.0.0
  description: cheztone frontends
services:
  lb1:
    scale: 1
    lb_config:
      port_rules:
      - source_port: 80
        selector: lb=true
        protocol: http