version: '2'
services:
  frontend:
    image: cheztone/cheztone-frontend
    labels:
      lb: true
  game:
    image: cheztone/cheztone-nuts
    labels:
      lb: true
  dev:
    image: cheztone/cheztone-front
    labels:
      lb: true