version: '2'
catalog:
  name: cheztone-front
  version: 1.0.0
  description: cheztone frontends
services:
  frontend:
    scale: 1
    lb_config:
      port_rules:
      - target_port: 80
        hostname: cheztone.org
  game:
    scale: 1
    lb_config:
      port_rules:
      - target_port: 80
        hostname: game.cheztone.org
  dev:
      scale: 1
      lb_config:
        port_rules:
        - target_port: 80
          hostname: dev.cheztone.org