.catalog:
  name: Jenkins
  version: 2.19.4-rancher1
  description: |
    Jenkins CI management server.
jenkins-primary:
  metadata:
    plugins: |
      ${plugins}
  lb_config:
        port_rules:
        - target_port: 8080
          hostname: jenkins.${host_domain}